---
- hosts: all
  sudo: true
  vars:
    web_server: nginxphp
    servername: tgif.dev www.tgif.dev 172.22.22.23
    timezone: UTC
  vars_files:
    - vars/mariadb.yml
    - vars/common.yml
    - [ "vars/nginxphp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - nginx
    - php5-fpm
    - mariadb
    - phpcommon
    - php-pecl
    - app
