---

- name: phpmyadmin | Install dbconfig-common
  apt: pkg=dbconfig-common state=latest install_recommends=no
  
- name: phpmyadmin | Pre-configure mysqladmin
  template: src=db_config.phpmyadmin.conf.j2
            dest=/etc/dbconfig-common/phpmyadmin.conf
            owner=root group=root mode=0600

- name: phpmyadmin | Install PHPMyAdmin packages
  yum: pkg=phpmyadmin state=installed enablerepo=epel
  when: ansible_os_family == 'RedHat'

- name: phpmyadmin | Install phpmyadmin packages
  apt: pkg=phpmyadmin state=installed
  when: ansible_os_family == 'Debian'

- name: phpmyadmin| Create database for PHPMyAdmin
  mysql_db:
    name={{ phpmyadmin_control_database | default('phpmyadmin') }}
    state=present
    login_user=root
    login_password={{ mariadb.root_password }}
  register: phpmyadmin_database

- name: phpmyadmin | Import PHPMyAdmin schema
  mysql_db:
    name={{ phpmyadmin_control_database | default('phpmyadmin') }}
    state=import
    target=/usr/share/doc/phpmyadmin/examples/create_tables.sql.gz
    login_user=root
    login_password={{ mariadb.root_password }}
  when: phpmyadmin_database is defined and phpmyadmin_database.changed == True

- name: phpmyadmin | Create PHPMyAdmin control user
  mysql_user:
    name={{ phpmyadmin_control_user | default('phpmyadmin') }}
    state=present
    password={{ phpmyadmin_control_password }}
    priv='{{ phpmyadmin_control_database | default('phpmyadmin') }}.*:ALL'
    login_user=root
    login_password={{ mariadb.root_password }}

- name: phpmyadmin | Modify config file (phpMyAdmin naming conventions changed)
  lineinfile: >
    dest=/etc/phpmyadmin/config.inc.php
    state=present
    regexp="^    \$cfg\['Servers'\]\[\$i\]\['{{ item.key }}'\].+$"
    line="    $cfg['Servers'][$i]['{{ item.key }}'] = '{{ item.value }}';"
    insertbefore="^\?>"
  with_items:
  - { key: bookmarktable, value: "pma__bookmark" }
  - { key: relation, value: "pma__relation" }
  - { key: table_info, value: "pma__table_info" }
  - { key: table_coords, value: "pma__table_coords" }
  - { key: pdf_pages, value: "pma__pdf_pages" }
  - { key: column_info, value: "pma__column_info" }
  - { key: history, value: "pma__history" }
  - { key: table_uiprefs, value: "pma__table_uiprefs" }
  - { key: designer_coords, value: "pma__designer_coords" }
  - { key: tracking, value: "pma__tracking" }
  - { key: userconfig, value: "pma__userconfig" }
  - { key: recent, value: "pma__recent" }
#    regexp="^.+\['{{ item.key }}'\].+$"
#  - { key: host, value: "{{ phpmyadmin_mysql_host }}" }
#  - { key: port, value: "{{ phpmyadmin_mysql_port }}" }
#  - { key: socket, value: "{{ phpmyadmin_mysql_socket }}" }
#  - { key: connect_type, value: "{{ phpmyadmin_mysql_connect_type }}" }
#  - { key: user, value: "{{ phpmyadmin_mysql_user }}" }
#  - { key: password, value: "{{ phpmyadmin_mysql_password }}"}

- name: phpmyadmin | Add site to nginx
  sudo: yes
  template:
    src=nginx.phpmyadmin.j2
    dest={{ws_vhost_path}}/phpmyadmin
  notify: restart nginx

- name: phpmyadmin | Enable site in nginx
  sudo: yes
  file:
    src={{ws_vhost_path}}/phpmyadmin
    dest={{ws_enabled_path}}/phpmyadmin
    state=link
  notify: restart nginx

